queue_rules:
  - name: default
    conditions:
      - "check-success=Nix Flake Check"

defaults:
  actions:
    queue:
      allow_merging_configuration_change: true

pull_request_rules:
  - name: Automerge PRs using the merge queue
    conditions:
      - "label=merge-queue"
      - "base=main"
    actions:
      queue:
        name: default

  - name: Delete head branch after merge
    conditions:
      - "merged"
    actions:
      delete_head_branch:
