name: Nix Flake Check

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  nix-flake-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Nix
      uses: aldoborrero/use-nix-action@v4
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Run nix flake check
      run: nix flake check

